# Generated by Django 5.1.4 on 2024-12-13 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormsGestion', '0002_remove_formfield_structure_fieldgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FormsGestion.fieldgroup'),
        ),
    ]
