# Generated by Django 5.1.4 on 2024-12-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormsGestion', '0003_alter_formfield_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
