# Generated by Django 5.1.4 on 2024-12-13 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormsGestion', '0004_formfield_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='formstructure',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
