# Generated by Django 5.1.4 on 2024-12-13 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormsGestion', '0005_formstructure_date'),
        ('SessionManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formstructure',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SessionManager.users'),
        ),
    ]
